In [1]:
!pip install pandas pyarrow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/m3/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: pyarrow in /Users/m3/Library/Python/3.9/lib/python/site-packages (21.0.0)
Requirement already satisfied: numpy>=1.22.4 in /Users/m3/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/m3/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/m3/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /Users/m3/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)

In [3]:
#transform parquet file to csv

import pandas as pd
parquet_file_path = 'dpwh_transparency_data.parquet'
csv_output_path = 'dpwh_transparency_data.csv'
df = pd.read_parquet(parquet_file_path)
df.to_csv(csv_output_path, index=False)
print(f"Successfully converted '{parquet_file_path}' to '{csv_output_path}'")

Successfully converted 'dpwh_transparency_data.parquet' to 'dpwh_transparency_data.csv'

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv('dpwh_transparency_data.csv')
df.head()

/var/folders/0l/x1pf8gvx5bg8r1z82xwj121c0000gn/T/ipykernel_17677/1789832323.py:4: DtypeWarning: Columns (16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('dpwh_transparency_data.csv')

,contractId,description,category,componentCategories,status,budget,amountPaid,progress,location,contractor,...,programName,sourceOfFunds,isLive,livestreamUrl,livestreamVideoId,livestreamDetectedAt,latitude,longitude,reportCount,hasSatelliteImage
0,21NA0052,"CONCRETING OF BRGY. MARAIGING FMR, BRGY. MARAI...",Roads,Roads,Completed,11939997.93,0,100.0,"{'province': 'Agusan del Norte DEO', 'region':...",C'ZARLES CONSTRUCTION & SUPPLY (23426),...,Outside Infra,Outside Infra - GAA 2021 DA FMR,False,NaN,NaN,NaN,9.367491,125.574854,0,True
1,23LF0026,BAGUAN BR. (B00119MN) ALONG SURIGAO DEL SUR BD...,Bridges,Bridges,Completed,4891483.94,0,100.0,"{'province': 'Davao Oriental 1st DEO', 'region...",ELLE-BUILDERS AND CONSTRUCTION SUPPLY (42245),...,Regular Infra,Regular Infra - GAA 2023 OO-1,False,NaN,NaN,NaN,7.034717,126.411111,0,True
2,25DI0029,OFF-CARRIAGEWAY IMPROVEMENT - TERTIARY ROADS -...,Roads,Roads,On-Going,36087410.00,0,0.0,"{'province': 'Laguna 2nd DEO', 'region': 'Regi...",MAGNA RICH TRADING & CONSTRUCTION (29108),...,Regular Infra,Regular Infra - GAA 2025 OO-1,False,NaN,NaN,NaN,14.173394,121.222769,0,True
3,24JE0007,BASIC INFRASTRUCTURE PROGRAM CONSTRUCTION OF R...,Roads,Roads,Completed,9889747.70,0,100.0,"{'province': 'Zamboanga del Sur 1st DEO', 'reg...",ZMS CONST. & DEV. CORP. (FORMERLY:ZMS CONSTRUC...,...,Regular Infra,Regular Infra - GAA 2024 SSP,False,NaN,NaN,NaN,8.036563,123.538867,0,True
4,20DJ0036,OO1: ENSURE SAFE AND RELIABLE NATIONAL ROAD SY...,Roads,Roads,Completed,28719880.00,0,100.0,"{'province': 'Quezon 2nd DEO', 'region': 'Regi...",ROMHEAD S.J. BUILDERS AND DEVELOPMENT INCORPOR...,...,Regular Infra,Regular Infra - GAA 2020 OO-1,False,NaN,NaN,NaN,13.930895,121.450798,0,True

In [5]:
#I used this to check if there are null values in each columns and to see the datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248220 entries, 0 to 248219
Data columns (total 23 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   contractId            248220 non-null  object
 1   description           248220 non-null  object
 2   category              248220 non-null  object
 3   componentCategories   241628 non-null  object
 4   status                248220 non-null  object
 5   budget                248220 non-null  float64
 6   amountPaid            248220 non-null  int64
 7   progress              248220 non-null  float64
 8   location              248220 non-null  object
 9   contractor            241613 non-null  object
 10  startDate             240752 non-null  object
 11  completionDate        206026 non-null  object
 12  infraYear             248220 non-null  int64
 13  programName           241621 non-null  object
 14  sourceOfFunds         241621 non-null  object
 15  isLive                248220 non-null  bool
 16  livestreamUrl         184 non-null     object
 17  livestreamVideoId     184 non-null     object
 18  livestreamDetectedAt  189 non-null     object
 19  latitude              214747 non-null  float64
 20  longitude             214747 non-null  float64
 21  reportCount           248220 non-null  int64
 22  hasSatelliteImage     248220 non-null  bool
dtypes: bool(2), float64(4), int64(3), object(14)
memory usage: 40.2+ MB

In [6]:
#I used this to check the statistical summary of the numerical columns in the dataset, including count, mean, standard deviation, minimum, 25th percentile, median, 75th percentile, and maximum values.
df.describe()

,budget,amountPaid,progress,infraYear,latitude,longitude,reportCount
count,2.482200e+05,248220.0,248220.000000,248220.000000,214747.000000,214747.000000,248220.000000
mean,2.569930e+07,0.0,92.225023,2020.650306,12.376540,122.623742,0.002836
std,6.297657e+07,0.0,24.060084,2.909421,3.425990,1.847971,0.065040
min,0.000000e+00,0.0,-100.000000,2016.000000,4.669481,116.967524,0.000000
25%,3.215446e+06,0.0,100.000000,2018.000000,9.562059,121.002010,0.000000
50%,9.594195e+06,0.0,100.000000,2021.000000,13.131199,122.312649,0.000000
75%,2.943136e+07,0.0,100.000000,2023.000000,14.861683,124.243069,0.000000
max,1.323000e+10,0.0,100.000000,2026.000000,21.118002,126.599555,12.000000

In [10]:
#I used this to check the number of rows and columns in the dataset, which is important for understanding the size and structure of the data.
df.shape
print("Number of columns:",df.shape[1])
print("Number of rows:",df.shape[0])

Number of columns: 23
Number of rows: 248220

In [15]:
#Since there are columns that are mostly empty or have a zero variable, we can drop those columns
#We also deleted the amountPaid since the min, max, and mean of it are all zero.
columns_to_drop = ['livestreamUrl', 'livestreamVideoId', 'livestreamDetectedAt','amountPaid']
df.cleaned = df.drop(columns=columns_to_drop)
print("Columns dropped successfully. Remaining columns:", df.cleaned.shape[1])

Columns dropped successfully. Remaining columns: 19